version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nextjs_prisma_db
    environment:
      POSTGRES_USER: hoangphong
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nextjs_prisma_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data: 